apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBMoPXbIxasJxnmBQEi9ftrnSD+zLKpoL7H54DROcJG653dKgONfPKow9Z9RGPwynXUKOOjkfN/kLafKs+iZCaDtqLs+XleK+ECb8IUJ3zT4q65sF3yWx42r7FmmbZxUWW7xBHyVx7LxziuxbnRXGtF/zH4vm/yoF8vB4Ogim98UDJohcwWWtKATkafIwwnqUUpWVRZWQBFWtYfFN9U80oIWterkh8w9+LsIn/w9KSDM7CLDyI0h4eZIqnoEz49y5Naxuztx2C4Q4SxPoYuZ4ePkYHi7gKBuMntP5kVO9w8WIvQDg0/XYearlNeVV1Hh7b6j6nU6DhOpktzeQoDWEhJj6hh+x+kuEwshgyrz/d6bFSdy6XpbF36PnMdrr6tNrRu0vByLmCM/GB0YIJZoQf4Nd9QOc+VYzOM2IRYikeVaPOBi6GxDi6zMx70lD0nKTGgLWwI8qp5GOCXRfaLvhbdpKGW5UNBBIPdrbSdQMql4noiigr56KmJ6fXdv56P0zG7P5QZNO0ioRuhWmia5heKmhYKJnEH3qC+8Hvl+aHiANgJT0gKxfVqtwHZboiJ9doGBAagiF9omjPucpUHobkSx7pS8Bynj0Qv50xuu67wi0kMDGRTGV/jD4bjAvKd9wPt8STKGlNna0/qzHSqVE3CENqMTinwm7EcPeqER16YX5aYcuttSFc19NpkI73f554trorxWCIg2om4ECDCszNU7U5d0Mc=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
